// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2SWi72M2-ij8t6Jw35jfWWm1hc658SsE',
    appId: '1:1018261381019:web:82404751a8c15d4c5f4b3e',
    messagingSenderId: '1018261381019',
    projectId: 'ragos53',
    authDomain: 'ragos53.firebaseapp.com',
    storageBucket: 'ragos53.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANgXET9b1lg002ySKHziX7c82-JrFTP90',
    appId: '1:1018261381019:android:ab489232948663c25f4b3e',
    messagingSenderId: '1018261381019',
    projectId: 'ragos53',
    storageBucket: 'ragos53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7b57m7enlARu4-1S2chvQv_6i3abeORk',
    appId: '1:1018261381019:ios:bcefd831d0f610105f4b3e',
    messagingSenderId: '1018261381019',
    projectId: 'ragos53',
    storageBucket: 'ragos53.firebasestorage.app',
    iosBundleId: 'com.example.ragos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7b57m7enlARu4-1S2chvQv_6i3abeORk',
    appId: '1:1018261381019:ios:bcefd831d0f610105f4b3e',
    messagingSenderId: '1018261381019',
    projectId: 'ragos53',
    storageBucket: 'ragos53.firebasestorage.app',
    iosBundleId: 'com.example.ragos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2SWi72M2-ij8t6Jw35jfWWm1hc658SsE',
    appId: '1:1018261381019:web:34af92a8ca2089d75f4b3e',
    messagingSenderId: '1018261381019',
    projectId: 'ragos53',
    authDomain: 'ragos53.firebaseapp.com',
    storageBucket: 'ragos53.firebasestorage.app',
  );
}
